allowBuilds:
  unrs-resolver: true
storeDir: .pnpm-store
minimumReleaseAgeExclude:
  - '@types/react-dom@19.2.7'
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - vitest@5.0.0
  - postcss@8.5.28
